apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnsi-controller-manager
  namespace: cnsi-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-native-security-inspector-portal-serviceaccount
  namespace: cnsi-system
---
