apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: cnsi-controller
  name: cnsi-controller-manager-metrics-service
  namespace: cnsi-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: cnsi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: cnsi-exporter-service
  namespace: cnsi-system
spec:
  ports:
    - name: http
      port: 6780
      targetPort: http
  selector:
    control-plane: cnsi-exporter
---
