# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
swagger: "2.0"
info:
  description: "APIs for Kubenetes security inspector (cnsi)."
  version: "v1alpha1"
  title: "cnsi APIs"
  contact:
    email: "loneghost1982@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9090"
basePath: "/api/v1"
tags:
  - name: "assessment"
    description: "assessments of workloads running in the Kubenetes cluster"
schemes:
  - "https"
  - "http"
paths:
  /:
    get:
      summary: "Check heathy of API server"
      description: ""
      operationId: "healthZ"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/StatusResponse"
  /namespaces:
    get:
      tags:
        - "assessment"
      summary: "List all the namespaces with inspection policies from the K8s cluster"
      description: ""
      operationId: "listNamespaces"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "500":
          description: "Internal server error occurred"
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NSWithPolicies"
      security:
        - api_key: []
  /namespaces/{ns}/assessments/{policy}:
    get:
      tags:
        - "assessment"
      summary: "Get inspection policy info under the namespace"
      description: "The related assessments of the workloads under the namespace are returned"
      operationId: "getNSAssessment"
      produces:
        - "application/json"
      parameters:
        - name: "ns"
          in: "path"
          description: "namespace name"
          required: true
          type: "string"
        - name: "policy"
          in: "path"
          description: "inspection policy name"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AssessmentResponse"
        "400":
          description: "Bad request"
        "500":
          description: "Internal server error occurred"
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  NSWithPolicies:
    type: "object"
    properties:
      name:
        type: "string"
        description: "name of inspection policies applied to the namespace"
      policies:
        type: "array"
        items:
          type: "string"
  Details:
    type: "object"
    required:
      - "workload"
      - "container"
      - "failure"
    properties:
      workload:
        type: "string"
      container:
        type: "string"
      dimension:
        type: "string"
      baseline:
        type: "string"
      failure:
        type: "string"
  Enforcement:
    type: "object"
    required:
      - "kind"
      - "status"
    properties:
      kind:
        type: "string"
      settings:
        type: "string"
      status:
        type: "string"
  AssessmentResponse:
    type: "object"
    properties:
      passed:
        type: "boolean"
      total:
        type: "integer"
        format: "int32"
      vulnerable:
        type: "integer"
        format: "int32"
      details:
        type: "array"
        items:
          $ref: "#/definitions/Details"
      enforcements:
        type: "array"
        items:
          $ref: "#/definitions/Enforcement"
  StatusResponse:
    type: "object"
    properties:
      status:
        type: "string"
      timestamp:
        type: "string"