# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspector-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - goharbor.goharbor.io
  resources:
    - assessmentreports
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - inspectionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - inspectionpolicies/status
  verbs:
  - get
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
