# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inspector-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inspector-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cronjobs