# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    control-plane: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090