# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
# permissions for end users to view inspections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspection-viewer-role
rules:
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - inspections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.goharbor.io
  resources:
  - inspections/status
  verbs:
  - get
