name: UNIT TEST

on:
  workflow_dispatch:
#   pull_request:
#   push:
#     paths-ignore:
#     - 'docs/**'

jobs:
  unit_test:
    runs-on:
      - ubuntu-latest
    timeout-minutes: 100
    
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}
          
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
           go-version: 1.16.15
        id: go

      - name: Config Go env
        run: |
          cd ${{ github.repository }}
          pwd
          go env
          echo "GOPATH=$(go env GOPATH):$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
        
      - name: Unit test
        run: |
          cd ${{ github.repository }}/src
          make test

      - name: Codecov For BackEnd
        uses: codecov/codecov-action@v1
        with:
          file: ${{ github.repository }}/src/cover.out
          flags: unittests
