name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - 'docs/**'
    
jobs:
  UTTEST:
    env:
       UTTEST: true
    runs-on:
      - ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
           go-version: 1.16.15
        id: go
      - name: setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 20.04
          docker_channel: stable
      - uses: actions/checkout@v2
        with:
         path: src/github.com/vmware-tanzu/cloud-native-security-inspector
      - name: setup env
        run: |
          cd src/github.com/vmware-tanzu/cloud-native-security-inspector
          pwd
          go env
          echo "GOPATH=$(go env GOPATH):$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: install
        run: |
          set -x
          cd src/github.com/vmware-tanzu/cloud-native-security-inspector
          pwd
          env
          chmod +x deploy.sh
          ./deploy.sh install

          IP=`hostname -I | awk '{print $1}'`
          echo '{"insecure-registries" : ["'$IP':5000"]}' | sudo tee /etc/docker/daemon.json
          echo "IP=$IP" >> $GITHUB_ENV

          sudo service docker restart
