# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
version: "3.3"
services:
  frontend:
    build:
      context: ../
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - frontend
volumes:
  server_db: {}
